home/views.py
from flask import Blueprint, render_template

home_blueprint = Blueprint('home', __name__)

from .forms import LoginForm, RegisterForm,UpdateForm

from .models import  get_user_by_username, get_user_by_username_and_password
from werkzeug.security import generate_password_hash

from flask_login import login_user, login_required, logout_user
from flask_login import current_user

from db.db_connection import get_connection

from flask_sqlalchemy import SQLAlchemy
from flask import (redirect, render_template, request, 
                Blueprint, url_for)

from .forms import get_user_by_email
from .views import get_connection

from flask import current_app, flash, request
import requests


# Resto del código del archivo forms.py


######## Rutas publicas
@home_blueprint.route('/', methods=['GET', 'POST'])
def index():

    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = get_user_by_username_and_password(username, password)

        if user:
            login_user(user)

            if user.tipo == 'Direccion':
                next = request.args.get('next')
                return redirect(next or url_for('home.User', _external=True, _scheme='http'))
            elif user.tipo == 'Area':
                next = request.args.get('next')
                return redirect(next or url_for('home.Area', _external=True, _scheme='http'))
            elif user.tipo == 'Administrador':
                next = request.args.get('next')
                return redirect(next or url_for('home.Admin', _external=True, _scheme='http'))
        else:
            flash("Acceso denegado. Por favor, verifica tus credenciales.", "danger")

    return render_template('auth/login.html', form=form)





from reportlab.pdfgen import canvas

from flask import send_file
from io import BytesIO
from reportlab.pdfgen import canvas

from flask_mail import Message
from io import BytesIO
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# ...

def get_user_by_email(email):
    conn = get_connection()
    with conn.cursor() as cursor:
        sql = "SELECT * FROM Usuario WHERE email = %s"
        cursor.execute(sql, (email,))
        user = cursor.fetchone()
    return user
@home_blueprint.route('/register', methods=['GET', 'POST'])
def register():

    form = RegisterForm()
    conn = get_connection()
    with conn.cursor() as cursor:
        sql = "SELECT ID, nombre FROM Area"
        cursor.execute(sql)
        areas = cursor.fetchall()
    form.area.choices = [(g['ID'], g['nombre']) for g in areas]

    if form.validate_on_submit():
        username = form.username.data
        nombre = form.nombre.data
        apellido_materno = form.apellido_materno.data
        apellido_paterno = form.apellido_paterno.data
        password = form.password.data
        email = form.email.data
        gender = form.gender.data
        area = form.area.data
        
        # Cifrado de contraseña
        hashed_password = generate_password_hash(password)

        conn = get_connection()
        with conn.cursor() as cursor:
            sql = "INSERT INTO Usuario (nombre, apellido_materno, apellido_paterno, contrasena, tipo, username, email, area) "
            sql += f"VALUES ('{nombre}', '{apellido_materno}', '{apellido_paterno}', '{hashed_password}', '{gender}', '{username}', '{email}','{area}')"
            cursor.execute(sql)
            conn.commit()

        # Generar el PDF con los datos del usuario
        pdf_buffer = generate_user_data_pdf(username, nombre, apellido_materno, apellido_paterno, password)

        # Enviar el correo electrónico con el PDF adjunto
        send_email_with_attachment(email, 'Datos de usuario', 'Adjuntamos los datos del usuario en formato PDF.', pdf_buffer, 'user_data.pdf')

        return redirect(url_for('home.Admin'))

    return render_template('auth/register.html', form=form)


def generate_user_data_pdf(username, nombre, apellido_materno, apellido_paterno, password):
    # Generar el PDF con los datos del usuario utilizando una librería como ReportLab o PyPDF2
    # Aquí tienes un ejemplo básico utilizando ReportLab
    from reportlab.pdfgen import canvas

    buffer = BytesIO()

    p = canvas.Canvas(buffer)
    p.drawString(100, 100, f'Username: {username}')
    p.drawString(100, 120, f'Nombre: {nombre}')
    p.drawString(100, 140, f'Apellido Paterno: {apellido_paterno}')
    p.drawString(100, 160, f'Apellido Materno: {apellido_materno}')
    p.drawString(100, 180, f'Contraseña: {password}')
    p.showPage()
    p.save()

    buffer.seek(0)
    return buffer

#iJh_geQgN4ss!Xr
def send_email_with_attachment(to_email, subject, body, attachment_data, attachment_filename):
    # Configurar los detalles de conexión del servidor SMTP
    smtp_host = 'smtp.gmail.com'
    smtp_port = 587
    smtp_username = '@gmail.com'  # Inserta tu dirección de correo electrónico de Gmail, este correo es el de la organizacion en general,o simplemente se debe crear para esta aplicacion
    smtp_password = 'msfechovcuaflztf'  # Inserta tu contraseña de correo electrónico válida , debe ser clave de aplicasion como lo indica em el manual 

    # Crear el objeto del mensaje
    msg = MIMEMultipart()
    msg['From'] = smtp_username
    msg['To'] = to_email
    msg['Subject'] = subject

    # Agregar el cuerpo del mensaje
    msg.attach(MIMEText(body, 'plain'))

    # Agregar el archivo adjunto
    attachment = MIMEBase('application', 'octet-stream')
    attachment.set_payload(attachment_data.getvalue())
    encoders.encode_base64(attachment)
    attachment.add_header('Content-Disposition', f'attachment; filename={attachment_filename}')
    msg.attach(attachment)

    # Conectar y enviar el correo electrónico
    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.starttls()
        server.login(smtp_username, smtp_password)
        server.sendmail(smtp_username, to_email, msg.as_string())


@home_blueprint.route('/register/delete/<int:user_id>', methods=['POST'])
def delete_user(user_id):
    conn = get_connection()
    with conn.cursor() as cursor:
        sql = "DELETE FROM Usuario WHERE ID = %s"
        cursor.execute(sql, (user_id,))
        conn.commit()
    return redirect(url_for('auth.usuarios'))

@home_blueprint.route('/register/update/<int:user_id>', methods=['GET', 'POST'])
def update_user(user_id):
    print("Entro a la función update_user")
    conn = get_connection()
    with conn.cursor() as cursor:
        # Obtener los datos del usuario a actualizar
        sql = "SELECT * FROM Usuario WHERE ID = %s"
        cursor.execute(sql, (user_id,))
        user = cursor.fetchone()

    form = UpdateForm()
    conn = get_connection()
    with conn.cursor() as cursor:
        sql = "SELECT ID, nombre FROM Area"
        cursor.execute(sql)
        areas = cursor.fetchall()
    form.area.choices = [(g['ID'], g['nombre']) for g in areas]

    if request.method == 'POST' and form.validate_on_submit():
        username = form.username.data

        # Verificar si el nuevo nombre de usuario ya está en uso por otro usuario
        if username != user['username']:  # Verifica si el nuevo nombre es diferente del nombre actual
            conn = get_connection()
            with conn.cursor() as cursor:
                sql = "SELECT * FROM Usuario WHERE ID != %s AND username = %s"
                cursor.execute(sql, (user_id, username))
                existing_user = cursor.fetchone()

            if existing_user:
                flash('El nombre de usuario ya está en uso. Por favor, elija otro.')
                return render_template('auth/update_user.html', form=form, user=user)

        # Si el nuevo nombre de usuario está disponible o no se ha cambiado, proceder con la actualización
        nombre = form.nombre.data
        apellido_materno = form.apellido_materno.data
        apellido_paterno = form.apellido_paterno.data
        password = form.password.data
        gender = form.gender.data
        area = form.area.data
       
        # Cifrado de contraseña
        hashed_password = generate_password_hash(password)

        conn = get_connection()
        with conn.cursor() as cursor:
            sql = "UPDATE Usuario SET username = %s, nombre = %s, apellido_materno = %s, apellido_paterno = %s, contrasena = %s, tipo = %s,area = %s WHERE ID = %s"
            cursor.execute(sql, (username, nombre, apellido_materno, apellido_paterno, hashed_password, gender,area,user_id))
            conn.commit()

        flash('Usuario actualizado con éxito.')
        return redirect(url_for('home.Admin'))

    # Rellenar el formulario con los datos del usuario a actualizar
    form.username.data = user['username']
    form.nombre.data = user['nombre']
    form.apellido_materno.data = user['apellido_materno']
    form.apellido_paterno.data = user['apellido_paterno']
    form.gender.data = user['tipo']
    form.area.data = user['area']

    return render_template('auth/update_user.html', form=form, user=user)




@home_blueprint.route('/contact')
def contact():
    return render_template('home/contact.html')

@home_blueprint.route('/manual')
def manual():
    
    return render_template('home/manual.html')

@home_blueprint.route('/Seguridad')
def Seguridad():
    
    return render_template('home/Seguridad.html')


@home_blueprint.route('/Acerca_de')
def Acerca_de():
    
    return render_template('home/Acerca_de.html')





import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

import base64
import os
import io
import base64
import pandas as pd

def grafica():
    # Crear un cursor
    conn = get_connection()
    with conn.cursor() as cursor:
        # Ejecutar una consulta para seleccionar todos los datos de la vista
        sql = "SELECT * FROM Material"
        cursor.execute(sql)

        # Recuperar los resultados

templates/base.html
<!DOCTYPE html>


<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"

        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ url_for ('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url_for('home.redirect_route') }}">
                <div class="sidebar-brand-icon rotate-n-15">
                    
                </div>
                <div class="sidebar-brand-text mx-3"><img class="img-fluid" src="/static/img/banner_2022_4_12_1649782448.4563.jpg" alt=""></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('home.redirect_route') }}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Index</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Manuales</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="{{ url_for('home.manual') }}">Manual</a>
                        <a class="collapse-item" href="{{ url_for('home.Seguridad') }}">Seguridad</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

        

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('home.contact') }}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Contacto</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('home.Acerca_de') }}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Acerca de</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="img/undraw_rocket.svg" alt="...">
                <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
                <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div class="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                   
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - Alerts -->
                      

                        <!-- Nav Item - Messages -->
                        

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small"></span>
                                <img class="img-profile rounded-circle"
                                    src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{{url_for('home.user')}}">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ url_for('auth.logout') }}" onclick="return confirm('¿Estás seguro de cerrar sesión?')">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Cerrar sesión
                                </a>
                                
                            </div>
                        </li>
                        
                    </ul>

                </nav>
                <!-- End of Topbar -->
                
            </div>
            {% block content %}
            {% endblock %}
<!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ url_for ('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for ('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ url_for ('static', filename= 'vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ url_for ('static', filename='js/sb-admin-2.min.js') }}"></script>

    <!-- Page level plugins -->
    <script src="{{ url_for ('static', filename='vendor/chart.js/Chart.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ url_for ('static', filename='js/demo/chart-area-demo.js') }}"></script>
    <script src="{{ url_for ('static', filename='js/demo/chart-pie-demo.js') }}"></script>

</body>

</html>

templates/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>